<Project Sdk="Microsoft.NET.Sdk.Razor">
    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.12" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.19" />
        <PackageReference Include="Syncfusion.Licensing" Version="34.2.5" />
        <PackageReference Include="Syncfusion.Blazor.Grid" Version="34.2.5" />
        <PackageReference Include="Syncfusion.Blazor.Inputs" Version="34.2.5" />
        <PackageReference Include="Syncfusion.Blazor.Themes" Version="34.2.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NetWorthTracker.Models\NetWorthTracker.Models.csproj" />
        <ProjectReference Include="..\NetWorthTracker.Services.Api\NetWorthTracker.Services.Api.csproj" />
    </ItemGroup>
</Project>
