<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NetWorthTracker.Common\NetWorthTracker.Common.csproj" />
        <ProjectReference Include="..\NetWorthTracker.Data\NetWorthTracker.Data.csproj" />
        <ProjectReference Include="..\NetWorthTracker.Services\NetWorthTracker.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CsvHelper" Version="33.1.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.20" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


</Project>
