// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetWorthTracker.Data;

#nullable disable

namespace NetWorthTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829120711_CreateAccountTable")]
    partial class CreateAccountTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("NetWorthTracker.Data.Features.Account.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Dates", "[ClosedDate] IS NULL OR [ClosedDate] > [OpenDate]");

                            t.HasCheckConstraint("CK_Account_Name_Length", "length([Name]) <= 256");

                            t.HasCheckConstraint("CK_Account_Type_Values", "[Type] IN (1, 2)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
